name: Deploy to S3
on:
  push:
    branches:
      - main
    paths:
      - "next/**"
      - "**.yml"
  repository_dispatch:
    types: [update_content]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install Dependencies
        run: npm install --prefix ./next

      - name: Build
        run: npm run build --prefix ./next
