name: Deploy to S3
on:
  push:
    branches:
      - main
    paths:
      - "/next"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
